version: '3'

services:
    reverse-proxy:
        image: rsmarincu/nginx:latest
        build:
            context: ./src/reverse-proxy
        depends_on:
            - math-api
            - pandas-api
            - visualisation-api
            - database
            - graphql
        ports:
            - 80:80
        labels:
            kompose.service.type: nodeport
    math-api:
        image: rsmarincu/math-api:latest
        container_name: math-api
        build: 
            context: ./src/math
        ports:
            - 5000:5000
    pandas-api:
        image: rsmarincu/pandas-api:latest
        container_name: pandas-api
        build: 
            context: ./src/pandas
        ports:
            - 5001:5001
    visualisation-api:
        image: rsmarincu/visualisation-api:latest
        container_name: visualisation-api
        build: 
            context: ./src/visualisation
        ports:
            - 5002:5002
    database:
        image: neo4j:3.5.11
        container_name: database
        environment: 
            - NEO4J_AUTH=none
        ports:
            - 7474:7474
            - 7687:7687
        volumes: 
            - $HOME/neo4j/data:/data neo4j
    graphql:
        image: rsmarincu/graphql:latest
        container_name: graphql
        build:
            context: ./src/database
            dockerfile: Dockerfile
        environment: 
            - NEO4J_HOST=neo4j
            - NEO4J_PORT=7687
            - BIND_HOST=0.0.0.0
            - BIND_PORT=8080
            - PYTHONUNBUFFERED=1
        ports:
            - 8080:8080