version: '3'

services:
    reverse-proxy:
        image: fluxusregistry.azurecr.io/nginx:latest
        build:
            context: ./src/reverse-proxy
        depends_on:
            - math-api
            - pandas-api
        ports:
            - 80:80
    math-api:
        image: fluxusregistry.azurecr.io/math-api:latest
        container_name: math-api
        build: 
            context: ./src/math
        ports:
            - 5000:5000
    pandas-api:
        image: fluxusregistry.azurecr.io/pandas-api:latest
        container_name: pandas-api
        build: 
            context: ./src/pandas
        ports:
            - 5001:5001
