apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: visualisation-api
  name: visualisation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: visualisation-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: visualisation-api
    spec:
      containers:
      - image: fluxusregistry.azurecr.io/visualisation-api:latest
        imagePullPolicy: ""
        name: visualisation-api
        ports:
        - containerPort: 5002
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
