apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 6
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: fluxuscontainerregistry.azurecr.io/job-wq:latest
        env:
          - name: PYTHONUNBUFFERED
            value: "0"
      restartPolicy: Never