apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: neo4j-db
  name: neo4j-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: neo4j-db
    spec:
      containers:
      - name: neo4j
        image: neo4j:3.5.11
        env:
        - name: NEO4J_AUTH
          value: none
        ports: 
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        - containerPort: 7473
          name: https
        volumeMounts:
          - name: neo4j-data
            mountPath: "/var/lib/neo4j/data"
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-claim