apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  completions: 18
  parallelism: 18
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - env:
        - name: PYTHONUNBUFFERED
          value: '0'
        - name: SESSION_ID
          value: '21397'
        image: fluxuscontainerregistry.azurecr.io/job-wq:latest
        name: c
      restartPolicy: Never
  terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 10
